# Essential headers for guardedalloc (header-only)

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "essential_headers",
    hdrs = [
        "//source/blender/blenlib:BLI_compiler_attrs.h",
        "//source/blender/blenlib:BLI_sys_types.h",
    ],
    includes = [
        "source/blender/blenlib",
    ],
)
