# Mikktspace tangent calculation library

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "mikktspace",
    srcs = glob([
        "*.c",
        "*.cpp",
    ], allow_empty = True),
    hdrs = glob([
        "*.h",
        "*.hpp",
    ], allow_empty = True),
    includes = ["."],
)
